version: "3.7"
services:
    db:
      image: postgres
      container_name: TodoAppPostgresDB
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        POSTGRES_DB: TodoApp
      volumes:
        - ./pgdata:/var/lib/docker/postgresql/data
        - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
        - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/fill_tables.sql
      ports:
        - "5432:5432"
      networks:
        - mynetwork
    webapp:
      image: springmvc
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: MyTodoApp
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/TodoApp
      volumes:
        - ./logs:/var/lib/docker/springmvc/logs
      depends_on:
        - db
      ports:
        - "8080:8080"
      networks:
        - mynetwork
networks:
  mynetwork:
    driver: bridge